#! /bin/bash
# Run log files got from log_teststand.py on cms904usr manually
# manual [date1][date2]...: to execute dates
# manual -c DATE: to execute dates from DATE

if [ -z "$CMSSW_BASE" ]
then
    cd ~/work/test/CMSSW_7_4_7/src/
    eval `scramv1 runtime -sh`
    echo "set CMSSW_BASE to $CMSSW_BASE"
    cd $OLDPWD
fi

manualrun(){
if [ -z "$1" ]
then
    fol=`date +%y%m%d`
else
    fol=$1
fi
dir='~/hcal_teststand_scripts/data/ts_904/'$fol
loc='/tmp/'$USER'/cms904usr/'$fol
wwwd=$HOME'/www/cms904/'$fol
mkdir -p $loc
echo '    >> handling data for '$fol
scp cms904usr:$dir/*.log $loc >/dev/null 2>>$loc/$fol.log
if [ "$2" = "-i" ]
then
    python -i mkplots $loc
else
    ./mkplots $loc 2>>$loc/$fol.log
fi
mkdir -p $wwwd
cp $loc/*.png $wwwd
date>$wwwd/$fol.log
grep -v TCanvas $loc/$fol.log|grep -v TGraph >>$wwwd/$fol.log
rm -rf $loc
echo '    >> finished handling data for '$fol
}

if [ -z "$1" ]
then
    manualrun
    exit
fi
if [ "$1" = "-c" ]
then
    if [ -z $2 ]
    then
	echo ERROR: no starting date information
	exit
    fi
    declare -i nw=`date +%s`
    declare -i td=`date -d $2 +%s`
    while [ $td -lt $nw ]
    do
	manualrun `date -d @$td +%y%m%d`
	td=$(($td+86400))
    done
    exit
fi
declare -i ord=1
while [ $ord -le $# ]
do
    eval "manualrun \$$ord"
    ord=$(($ord+1))
done
