#! /bin/bash
# Run log files got from log_teststand.py on cms904usr regularly
# updates [n]: update the website every n hours

if [ -z "$CMSSW_BASE" ]
then
    cd ~/work/test/CMSSW_7_4_7/src/
    eval `scramv1 runtime -sh`
    echo "set CMSSW_BASE to $CMSSW_BASE"
    cd $OLDPWD
fi

manualrun(){
if [ -z "$1" ]
then
    fol=`date +%y%m%d`
    logst=`ssh cms904usr bin/stlog 2>&1`
else
    fol=$1
fi
dir='~/hcal_teststand_scripts/data/ts_904/'$fol
loc='/tmp/'$USER'/cms904usr/'$fol
wwwd=$HOME'/www/cms904/'$fol
mkdir -p $loc
echo '    >> handling data for '$fol
scp cms904usr:$dir/*.log $loc >/dev/null 2>>$loc/$fol.log
if [ "$2" = "-i" ]
then
    python -i mkplots $loc
else
    ./mkplots $loc 2>>$loc/$fol.log
fi
mkdir -p $wwwd
cp $loc/*.png $wwwd
date>$wwwd/$fol.log
echo "$logst" >>$wwwd/$fol.log
grep -v TCanvas $loc/$fol.log|grep -v TGraph>>$wwwd/$fol.log
rm -rf $loc
echo '    >> finished handling data for '$fol
}


if [ -z "$1" ]
then
    declare -i sec=$((2*3600))
else
    declare -i sec=$(($1*3600))
fi
while :
do
    nw=`date +%s`
    dt=`date +%y%m%d`
    st=`date -d $dt +%s`
    declare tm=$(($nw-$st))
    if [ $tm -lt $sec ]
    then
	date
	manualrun `date -d @$(($nw-86400)) +%y%m%d` &
    fi
    date
    manualrun &
    sleep $sec
done